[build]
  command = "pip install -r requirements.txt && python bot.py"
  publish = "."

[context.production.environment]
  BOT_TOKEN = "your_bot_token_here"
  API_ID = "your_api_id_here"
  API_HASH = "your_api_hash_here"
  FORCE_SUB = "your_force_sub_here"
  DB_NAME = "your_db_name_here"
  DB_URL = "your_db_url_here"
  START_PIC = "your_start_pic_here"
  ADMIN = "your_admin_here"
